language: ruby
rvm:
- 2.2

install:
- gem install jekyll jekyll-sitemap

before_script:
- git config --global user.name 'woliveiras'
- git config --global user.email 'w.oliveira542@gmail.com'

script:
- jekyll build

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch master --single-branch $DEPLOY . || (git init && git remote add -t master origin $DEPLOY)
- rm -rf ./*
- cp -r ../_site/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m master
- git push -q -u origin master